### ISSUE TITLE
No longer working for 1.21

### ISSUE THREAD

**Issue by yutotakano** [Programie/MatterBukkit#4]
Hi! This plugin has been the only Matterbridge plugin that has worked for us in our server, but unfortunately it appears to not be sending downward messages (Matterbridge -> Minecraft) since the 1.21 update. The opposite direction works. 

No errors are seen in the Matterbridge central console.

I've tried to compile MatterBukkit locally and find where the problem might be, but unfortunately some dependencies in the Maven project are private (`https://maven.pkg.github.com/Programie/Common` is 401 for me), and I could not get it to compile.

Would you mind looking into this?

**Comment by Programie** [comment]
Hi,
That sounds like something related to chat messages changed in 1.21. I will have a look.

> I've tried to compile MatterBukkit locally and find where the problem might be, but unfortunately some dependencies in the Maven project are private (https://maven.pkg.github.com/Programie/Common is 401 for me), and I could not get it to compile.

Ah yes, that issue again. I'm using the GitHub Package Registry as my Maven repository.. Unfortunately, it's not possible to access it without authentication. You have to create a Personal Access Token in your GitHub settings (see Developer settings at the bottom of the settings navbar) and use that in your `~/.m2/settings.xml`.
It's not the best experience by having to authenticate for a public repository, but at least much better than having to copy over stuff between all my projects. :smile:

**Comment by yutotakano** [comment]
Thanks for the prompt response! I got the compilation working with the PAT.

I don't want to disturb you too much, but I struggled to reproduce the issue in Docker due to my understanding of the setup... I can both send and receive messages from the terminal to MC by manually `curl`-ing the `:4241/api/messsages` endpoint, but I'm a bit confused as I thought `:4241` is for MatterBukkit to interface with and that I should be pretending to be Discord by interfacing with `:4242` instead (where neither works).

**Comment by Programie** [comment]
MatterBukkit uses the MatterBridge HTTP API which could listen on any port as configured in your MatterBridge configuration file. In fact, you can have configure multiple ports in your configuration. That's exactly what I'm using for my test setup as you can see that in the [docker-dev/matterbridge.toml](https://github.com/Programie/MatterBukkit/blob/master/docker-dev/matterbridge.toml) file.

In that case, port 4242 is used as the port used by MatterBukkit. On the other hand, port 4241 is used for clients like curl, or even another Minecraft server.

As far as I understood the MatterBridge API, each client should use a dedicated port. If I remember correctly, if there are multiple clients connected to the same port, the clients won't receive all messages in case of a streamed connection (`/api/stream`). That's the reason why there are two port configurations inside the [matterbridge.toml file](https://github.com/Programie/MatterBukkit/blob/master/docker-dev/matterbridge.toml).
You should be able to reproduce it if you connect two curl instances to the same port using `/api/stream` as the endpoint. Then send some messages to MatterBridge and they probably just appear in one of those two connected curl clients.

**Comment by Programie** [comment]
OK, good to know the plugin is working for you again.

Did you see any errors in the server log which could give a clue how this could have happened?

One thing I could imagine: The plugin might lost it's connection to MatterBridge but the connection was still alive in some way.

Usually, the plugin tries to reconnect in case any connection error occurs. But that should also log some exceptions in the server log.
